[registry_hosts]
# Liste des IPs (une par ligne)
51.44.184.112

[registry_hosts:vars]
# Variables communes à tous les hôtes du groupe
ansible_user=ubuntu
ansible_ssh_private_key_file=../infra/registry-key-terraform.pem
# On désactive la vérification de la clé hôte pour éviter le prompt "Yes/No"
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
