services:
  registry:
    image: registry:2
    restart: always
    # Port 5000 pas exposé publiquement, nginx proxy en interne
    expose:
      - "5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth:ro

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - registry
      - ui

  ui:
    image: joxit/docker-registry-ui:main
    restart: always
    expose:
      - "80"
    environment:
      - REGISTRY_TITLE=Ansible Deployed Registry
      - REGISTRY_URL=https://{{ public_ip }}
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    depends_on:
      - registry
