name: Deploy infrastructure on AWS EC2 instance

on:
  workflow_dispatch:

jobs:
  docker-build-and-deploy:
    name: 🐳 Build and deploy Docker images
    runs-on: ubuntu-latest
    env:
      REGISTRY_PUBLIC_IP: ${{ secrets.PRIVATE_REGISTRY_PUBLIC_IP }}
      REGISTRY_USERNAME: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build images
        run: docker compose build
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: $REGISTRY_PUBLIC_IP
          username: $REGISTRY_USERNAME
          password: $REGISTRY_PASSWORD
      - name: Tag and push images to private registry
        run: |
          # todo: create a SEMVER tag
          API_IMAGE="${REGISTRY_PUBLIC_IP}/api_python:latest"
          WEB_IMAGE="${REGISTRY_PUBLIC_IP}/web_react:latest"

          docker tag api_python "$API_IMAGE"
          docker tag web_react "$WEB_IMAGE"

          docker push "$API_IMAGE"
          docker push "$WEB_IMAGE"
